sonar.projectKey=fastapi-devops-pipeline
sonar.projectName=FastAPI DevOps Pipeline
sonar.sources=app
sonar.tests=tests
sonar.python.version=3.11
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8
sonar.qualitygate.wait=true
